### ISSUE TITLE
For now template requires users to provide `operationId` in their files

### ISSUE THREAD

**Issue by derberg** [derberg/python-mqtt-client-template#2]
We should recommend `operationId` but not fail if it is not there. The best would be if we have a fallback mechanism, like if there is no `operationId` we could grab operation name or something

related code https://github.com/derberg/python-mqtt-client-template/blob/main/components/TopicFunction.js#L32

**Comment by thulieblack** [comment]
As a lazy programmer, I'll start with this issue
