### ISSUE TITLE
see how we can support not only `publish` but also `subscribe` operations

### ISSUE THREAD

**Issue by derberg** [derberg/python-mqtt-client-template#4]
At the moment the generated client enables a set of functions that are generated out of `publish` operations, so user can use it to send messages.

We need to also explore how we could also generate `receive*` functions and do `ch.operations().filterBySend()` -> https://github.com/derberg/python-mqtt-client-template/blob/main/components/TopicFunction.js#L32C27-L32C60

**Comment by thulieblack** [comment]
Will pick this is my next issue
