### ISSUE TITLE
At the moment generated client uses paho module that needs to be also installed to use client

### ISSUE THREAD

**Issue by derberg** [derberg/python-mqtt-client-template#6]
In Nodejs we have `package.json` that enables us to specify dependencies for project. So user of client can do `npm install` and get all stuff installed, no need for separate installation of each dependency.

I bet there is something like this in Python, like `requirements.txt` or something else. We need nicer experience for the client user, so they can just do `from client import CommentsServiceClient` and somehow it works, they do not need to separately do pip installation of paho or anything else

**Comment by thulieblack** [comment]
Will also take this one too, as a starting point
